# File with sample name and barcode as first and second columns, respectively.
SAMPLE2BARCODE: "01.raw_data/sample2barcode.tsv"

# Forward and reverse reads
READ1: "01.raw_data/read1.fastq"
READ2: "01.raw_data/read2.fastq"

# Foward and reverse indices
INDEX1: "01.raw_data/index1.fastq"
INDEX2: "01.raw_data/index2.fastq"

# Tool specific parameters
parameters:
    # Primer Trimming
    fastx_truncate:
        len2trim: 20 # Primer length
    # Merge pairs
    fastq_mergepairs:
        max_diff: 25
        trunc_tail: 10
        min_overlap_len: 20
        min_merge_len: 200
    # Filter out Low quality sequences
    fastq_filter:
        max_ee: 0.5
        trunc_len: 200
    # Rarefy to even depth
    otutab_rare:
        depth: 3188 # Examine the file 14.Summarize_table/summary.txt to get this number
    # Assign Taxonomy 
    sintax:
        database: "/home/jeffbrady/refData/silva_16s_v123.fa" # 16S, 18S or ITS database
        cutoff: 0.8 # cutoff for assigning taxonomy for 0-1 for 0-100% identity

# Full paths to the specified programs
programs_path:
    usearch: "/usr/local/bin/usearch11"

