isExcel: False  # True or False
EXCEL_FILE: "01.raw_data/sample2barcode.tsv"

# Forward and reverse reads
READ1: "01.raw_data/read1.fastq"
READ2: "01.raw_data/read2.fastq"

# Foward and reverse indices
INDEX1: "01.raw_data/index1.fastq"
INDEX2: "01.raw_data/index2.fastq"

# List of Samples in the sample2barcode file "01.raw_data/sample2barcode.tsv" to be analyzed
SAMPLES: ["inital", "control", "A0_1", "A1", "A10", "A100", "S0_1", "S1", "S10", "S100"]

# Tool specific parameters
parameters:
    # Primer Trimming
    fastx_truncate:
        len2trim: 20 # Primer length
    # Merge pairs
    fastq_mergepairs:
        max_diff: 25
        trunc_tail: 10
        min_overlap_len: 20
        min_merge_len: 200
    # Filter out Low quality sequences
    fastq_filter:
        max_ee: 0.5
        trunc_len: 200
    # Rarefy to even depth
    otutab_rare:
        depth: 3188 # Exam the file 14.Summarize_table/summary.txt to ascertain the number
    # Assign Taxonomy 
    sintax:
        database: "/home/jeffbrady/refData/silva_16s_v123.fa" # 16S, 18S or ITS database
        cutoff: 0.8 # cutoff for assinging taxonomy for 0-1 for 0-100%

# Full paths to the specified programs
programs_path:
    usearch: "/usr/local/bin/usearch11"
    xlsx2csv: "/usr/bin/xlsx2csv" # sudo apt-get install xlsx2csv

